---
global:
  scrape_interval: 15s
  evaluation_interval: 15s
alerting:
  alertmanagers:
    - static_configs:
        - targets: null
rule_files: null
scrape_configs:
  - job_name: windows
    scrape_interval: 5s
    static_configs:
      - targets:
          - localhost:9182
